### ISSUE TITLE
XSHextract not working

### ISSUE THREAD

**Issue by keheintz** [jselsing/XSGRB_reduction_scripts#2]
Når jeg kører den nyeste version af XSHextract får jeg følgende fejlmeddelse:
AttributeError: 'list' object has no attribute 'split'

Traceback:
File "XSHextract.py", line 462, in <module>
    main(argv = sys.argv[1:])
  File "XSHextract.py", line 405, in main
    args.pol_degree = [ int(x) for x in args.pol_degree.split(",")]

Kører commandoen ved:
python XSHextract.py /Users/Kasper/GRBs/XSGRB/GRB110715A/UVBOB1skysub.fits --optimal --slitcorr --plot_ext

What to do?

**Comment by jselsing** [comment]
Try again after latest update and let me know if it fixed
