### ISSUE TITLE
stitch arms

### ISSUE THREAD

**Issue by keheintz** [jselsing/XSGRB_reduction_scripts#3]
Får følgende meddelse når jeg prøver at stitche de 3 arme sammen:
ValueError: operands could not be broadcast together with shapes (2816,) (2818,) 

med traceback:
  File "stitch_arms.py", line 155, in <module>
    main()
  File "stitch_arms.py", line 131, in main
    wl, flux, error = stitch_XSH_spectra(waves, flux, error)
  File "stitch_arms.py", line 56, in stitch_XSH_spectra
    uvbres = [np.sum(((f_uvb_ii - f_vis)__2)/(e_uvb__2 + e_vis_*2)) for ii in look_range]

**Comment by jselsing** [comment]
Try updating for the latest fix

**Comment by jselsing** [comment]
If the latest update solves your problem, please mark the issue as closed.
